
apiVersion: v1
kind: Service
metadata:
  name: plasma-lms-course-service
  namespace: lms-namespace
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app-name: plasma-lms-course-service