spring:
  application:
    name: course-service
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
      file-size-threshold: 1MB
      location: ${java.io.tmpdir}

  datasource:
    driver-class-name: org.postgresql.Driver  # Needed for DataSourceBuilder

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  web:
    resources:
      static-locations: classpath:/static/

aws:
  s3:
    bucket-name: plasma-lms-dev-bucket
  secretsmanager:
    region: us-west-2
    secretName: plasma_lms_db_user_dev_password


jwt:
  secret: bXlfc2VjcmV0X2tleV9teV9zZWNyZXRfa2V5X3Byb2R1Y3Rpb25fdXNlX3N0cm9uZ2VyX2tleV8yNTZfYml0c19sb25n
  issuer: https://auth.nucleusteq.com

gateway:
  validation:
    enabled: false
  secret:
    header: X-Gateway-Secret
    value: your-super-secret-gateway-key-change-this-in-production
  signature:
    header: X-Gateway-Signature

direct:
  secret:
    header: X-Direct-Secret
    value: your-super-secret-direct-key-change-this-in-production
