spring:
  application:
    name: course-service
  servlet:
    multipart:
      enabled: true  # Enables multipart file upload support
      max-file-size: -1  # Removes the individual file size limit
      max-request-size: -1  # Removes the total request size limit
      file-size-threshold: 1MB  # Stores files larger than 1MB to disk
      location: ${java.io.tmpdir}  # Uses the system's temporary directory for uploads

  datasource:
    url: jdbc:postgresql://localhost:5432/lms_test
    username: postgres
    password: anil@123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8080

jwt:
  secret: bXlfc2VjcmV0X2tleV9teV9zZWNyZXRfa2V5X3Byb2R1Y3Rpb25fdXNlX3N0cm9uZ2VyX2tleV8yNTZfYml0c19sb25n
  issuer: https://auth.nucleusteq.com

aws:
  s3:
    bucket-name: plasma-lms-dev-bucket
  secretsmanager:
    region: us-west-2
    secretName: plasma_lms_db_user_dev_password

gateway:
  validation:
    enabled: true
  secret:
    header: X-Gateway-Secret
    value: your-super-secret-gateway-key-change-this-in-production
  signature:
    header: X-Gateway-Signature

direct:
  secret:
    header: X-Direct-Secret
    value: your-super-secret-direct-key-change-this-in-production
