
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plasma-lms-course-service
  namespace: lms-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: plasma-lms-course-service 
  template:
    metadata:
      labels:
        app-name: plasma-lms-course-service 
    spec:
      serviceAccountName: plasma-lms-course-service-sa
      containers:
        - name: plasma-lms-course-service
          image: image_name
          resources:
            requests:
              cpu: 500m
              memory: 750Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          ports:
            - containerPort: 8080
          env:
            - name: env
              value: "dev"
            - name: AWS_ROLE_ARN
              value: arn:aws:iam::547568624982:role/plasma-lms-course-service-dev-pod-role
            - name: AWS_WEB_IDENTITY_TOKEN_FILE
              value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
            - name: AWS_ROLE_SESSION_NAME
              value: default-session
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          volumeMounts:
            - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              name: aws-iam-token
              readOnly: true
      volumes:
        - name: aws-iam-token
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: sts.amazonaws.com
                  expirationSeconds: 8640000
                  path: token